import React, { useState, useEffect } from "react";
import { useUser } from "@clerk/clerk-react";
import "./Save.css";
import dollarIcon from "../../assets/images/dollar-icon.png";

export default function Save() {

  // Helper function to safely convert localized digits (e.g. Hindi "१", "२" or comma string "10,000") to raw English Numbers
  const sanitizeNumberString = (str) => {
    if (!str && str !== 0) return 0;
    const strObj = typeof str === "number" ? str.toString() : String(str);

    // Replace indicative Indic numerals with ASCII
    const devanagariMap = { '०': '0', '१': '1', '२': '2', '३': '3', '४': '4', '५': '5', '६': '6', '७': '7', '८': '8', '९': '9' };
    let asciiStr = strObj.replace(/[०-९]/g, match => devanagariMap[match]);

    // Remove all commas and spaces generated by translators
    asciiStr = asciiStr.replace(/[, \s]/g, "");

    return Number(asciiStr) || 0;
  };

  const { user } = useUser();

  const [goals, setGoals] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [newGoal, setNewGoal] = useState({ title: "", target: "" });
  const [savingsInput, setSavingsInput] = useState({});

  const API = "http://localhost:5000/api/goals";


  /* FETCH GOALS */
  useEffect(() => {

    if (!user) return;

    const fetchGoals = async () => {

      try {
        const res = await fetch(`${API}/${user.id}`);
        const data = await res.json();

        // Normalize Decimal128 values from MongoDB
        const normalizedData = data.map(goal => {
          let normalizedGoal = { ...goal };
          if (goal.savedAmount && typeof goal.savedAmount === "object" && goal.savedAmount.$numberDecimal) {
            normalizedGoal.savedAmount = Number(goal.savedAmount.$numberDecimal);
          }
          if (goal.targetAmount && typeof goal.targetAmount === "object" && goal.targetAmount.$numberDecimal) {
            normalizedGoal.targetAmount = Number(goal.targetAmount.$numberDecimal);
          }
          return normalizedGoal;
        });

        setGoals(normalizedData);
      } catch (err) {
        console.error("Fetch error:", err);
      }

    };

    fetchGoals();

  }, [user]);


  /* ADD GOAL */
  const handleAddGoal = async () => {

    if (!newGoal.title || !newGoal.target) return;

    try {

      const goalToSave = {
        clerkId: user.id,
        title: newGoal.title,
        targetAmount: sanitizeNumberString(newGoal.target)
      };

      const res = await fetch(API, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(goalToSave)
      });

      const savedGoal = await res.json();

      if (savedGoal.savedAmount && typeof savedGoal.savedAmount === "object" && savedGoal.savedAmount.$numberDecimal) {
        savedGoal.savedAmount = Number(savedGoal.savedAmount.$numberDecimal);
      }
      if (savedGoal.targetAmount && typeof savedGoal.targetAmount === "object" && savedGoal.targetAmount.$numberDecimal) {
        savedGoal.targetAmount = Number(savedGoal.targetAmount.$numberDecimal);
      }

      setGoals([...goals, savedGoal]);
      setNewGoal({ title: "", target: "" });

    } catch (err) {
      console.error(err);
    }

  };


  /* ADD SAVINGS */
  const handleUpdateProgress = async (id) => {

    const amountToAdd = sanitizeNumberString(savingsInput[id]);

    if (!amountToAdd || isNaN(amountToAdd)) return;

    try {

      const res = await fetch(`${API}/add/${id}`, {

        method: "PUT",

        headers: { "Content-Type": "application/json" },

        body: JSON.stringify({ amount: amountToAdd })

      });

      const updatedGoal = await res.json();

      // If the backend returns a MongoDB Decimal128, it comes as an object {$numberDecimal: "500"}
      // We must normalize it to a raw number so the front-end math works!
      if (updatedGoal.savedAmount && typeof updatedGoal.savedAmount === "object" && updatedGoal.savedAmount.$numberDecimal) {
        updatedGoal.savedAmount = Number(updatedGoal.savedAmount.$numberDecimal);
      }
      if (updatedGoal.targetAmount && typeof updatedGoal.targetAmount === "object" && updatedGoal.targetAmount.$numberDecimal) {
        updatedGoal.targetAmount = Number(updatedGoal.targetAmount.$numberDecimal);
      }

      setGoals(goals.map(g => g._id === id ? updatedGoal : g));

      setSavingsInput({ ...savingsInput, [id]: "" });

    } catch (err) {
      console.error(err);
    }

  };


  /* DELETE GOAL */
  const handleDeleteGoal = async (id) => {

    try {

      await fetch(`${API}/${id}`, { method: "DELETE" });

      setGoals(goals.filter(g => g._id !== id));

    } catch (err) {
      console.error(err);
    }

  };


  /* SEARCH */
  const filteredGoals = goals.filter(g =>
    g.title.toLowerCase().includes(searchTerm.toLowerCase())
  );


  return (

    <div className="save-container">

      <header className="save-header centered">

        <div className="title-wrapper">

          <h1 className="save-title">Save Money</h1>

          <div className="dollar-badge">
            <img src={dollarIcon} alt="coin" className="coin-img" />
          </div>

        </div>

      </header>


      <main className="save-content">


        {/* CREATE GOAL */}

        <section className="goal-input-card">

          <h3 className="section-label">Create a New Saving Goal</h3>

          <div className="input-row">

            <input
              type="text"
              placeholder="Goal Name"
              value={newGoal.title}
              onChange={(e) =>
                setNewGoal({ ...newGoal, title: e.target.value })
              }
            />

            <input
              type="number"
              placeholder="Target Amount"
              value={newGoal.target}
              onChange={(e) =>
                setNewGoal({ ...newGoal, target: e.target.value })
              }
            />

            <button onClick={handleAddGoal} className="primary-btn">
              Set Goal
            </button>

          </div>

        </section>


        {/* SEARCH */}

        <input
          className="search-bar"
          placeholder="Search goals"
          onChange={(e) => setSearchTerm(e.target.value)}
        />


        {/* GOALS */}

        <div className="goals-grid">

          {filteredGoals.map((goal) => {

            // MATH FIX: Ensure values are safely parsed out of translated characters
            const saved = sanitizeNumberString(goal.savedAmount);
            const target = sanitizeNumberString(goal.targetAmount) || 1; // Prevent div by 0

            // Calculation: (Current / Total) * 100
            const rawPercentage = (saved / target) * 100;
            const percentage = Math.min(Math.round(rawPercentage), 100);

            const remaining = target - saved;
            const monthlyTip = Math.ceil(remaining / 6);
            const isCompleted = percentage >= 100;

            return (

              <div key={goal._id} className={`goal-card ${isCompleted ? 'goal-completed' : ''}`}>

                <button
                  className="delete-x"
                  onClick={() => handleDeleteGoal(goal._id)}
                >
                  ✕
                </button>

                <div className="goal-card-header">
                  <h2>{goal.title}</h2>
                  <p className="percentage-text">{percentage}% saved</p>
                </div>

                <p className="amount-display">
                  ₹{saved.toLocaleString("en-IN")} / ₹{target.toLocaleString("en-IN")}
                </p>


                {/* PROGRESS BAR */}

                <div className="progress-container">

                  <div
                    className="progress-bar"
                    style={{ width: `${percentage}%` }}
                  />

                </div>


                {/* SMART TIP */}

                {!isCompleted && (

                  <p className="saving-tip">
                    💡 Save ₹{monthlyTip.toLocaleString("en-IN")} monthly to reach your goal in 6 months
                  </p>

                )}


                {!isCompleted && (

                  <div className="update-controls">

                    <input
                      type="number"
                      placeholder="Add savings"
                      value={savingsInput[goal._id] || ""}
                      onChange={(e) =>
                        setSavingsInput({
                          ...savingsInput,
                          [goal._id]: e.target.value
                        })
                      }
                    />

                    <button
                      className="add-savings-btn"
                      onClick={() => handleUpdateProgress(goal._id)}
                    >
                      Add Savings
                    </button>

                  </div>

                )}

              </div>

            );

          })}

        </div>

      </main>

    </div>

  );

}